import { Poppins } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/client-layout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "X Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
